function PKG_PREFIX=on_uninstall(desc)
% This code remove the paths of OCTAVE "path" of all directory of code.
% this code should be run before uninstall bsltool package.
% cdesc =pkg('list','bsltl');desc=cdesc{1};

	disp('Uninstalled');
	PACKAGE    = getfield(desc,'name')
	VERSION    = getfield(desc,'version')
	PKG_PREFIX = getfield(desc,'dir')

	DIRECTORY={	['mfiles',filesep,'data'], ...
				['mfiles',filesep,'extras'], ...
				['mfiles',filesep,'filter'], ...
				['mfiles',filesep,'graphic'], ...
				['mfiles',filesep,'graphic',filesep,'moments'], ...
				['mfiles',filesep,'graphic',filesep,'others'], ...
				['mfiles',filesep,'graphic',filesep,'stats'], ...
				['mfiles',filesep,'numerical'], ...
				['mfiles',filesep,'numerical',filesep,'pmf'], ...
				['mfiles',filesep,'numerical',filesep,'thsp'], ...
				['mfiles',filesep,'numerical',filesep,'extras'], ...
				['mfiles',filesep,'quality'], ...
				['mfiles',filesep,'undocumented']};

	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	
	for k=1:length(DIRECTORY)
		rmpath([PKG_PREFIX,filesep,DIRECTORY{k}]);
	end
	
end
