use strict;


set_from_init_file('EXTRA_HEAD', "\
	<div class=\"top-nav darkblock\">\
       	<a href=\"http://www.nongnu.org/bsltl/index.html\">Home</a> |\
       	<a href=\"http://www.nongnu.org/bsltl/documentation.html\">Documentation</a> |\
       	<a href=\"http://www.nongnu.org/bsltl/overview.html\">Overview</a> |\
       	<a href=\"http://www.nongnu.org/bsltl/examples.html\">Examples</a> |\
       	<a href=\"http://git.savannah.gnu.org/cgit/bsltl.git/tree/\" target=\"_blank\">Code</a> |\
       	<a href=\"http://download.savannah.gnu.org/releases/bsltl/\" target=\"_blank\">Download</a> |\
       	<a href=\"https://savannah.nongnu.org/projects/bsltl/\" target=\"_blank\">Develop</a>\
	</div><br>");

set_from_init_file('EXTRA_HEAD', "\
  <STYLE> #jsMath_Warning {display: none} </STYLE>\
  <SCRIPT SRC=\"../../jsMath/easy/load.js\"></SCRIPT>");



